{"type": "error", "data": "Error in Umap", "stack": "Traceback (most recent call last):\n  File \"/root/GraphRAG-UI/GraphRAG-Local-UI/graphrag/graphrag/index/verbs/graph/layout/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n  File \"/root/GraphRAG-UI/GraphRAG-Local-UI/graphrag/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n  File \"/root/.conda/envs/graphrag-local/lib/python3.10/site-packages/umap/umap_.py\", line 2928, in fit_transform\n    self.fit(X, y, force_all_finite, **kwargs)\n  File \"/root/.conda/envs/graphrag-local/lib/python3.10/site-packages/umap/umap_.py\", line 2817, in fit\n    self.embedding_, aux_data = self._fit_embed_data(\n  File \"/root/.conda/envs/graphrag-local/lib/python3.10/site-packages/umap/umap_.py\", line 2865, in _fit_embed_data\n    return simplicial_set_embedding(\n  File \"/root/.conda/envs/graphrag-local/lib/python3.10/site-packages/umap/umap_.py\", line 1089, in simplicial_set_embedding\n    graph.data[graph.data < (graph.data.max() / float(n_epochs_max))] = 0.0\n  File \"/root/.conda/envs/graphrag-local/lib/python3.10/site-packages/numpy/core/_methods.py\", line 41, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n", "source": "zero-size array to reduction operation maximum which has no identity", "details": null}
